services:
  frontend:
    container_name: bricks-frontend
    build: frontend
    image: bricks-frontend:1.0.0
    ports:
      - "20080:80"
    depends_on:
      - mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    networks:
      - bricks-network

  backend:
    container_name: bricks-backend
    build: backend
    image: bricks-backend:1.0.0
    ports:
      - "21080:80"
    depends_on:
      - mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    networks:
      - bricks-network

  mysql:
    container_name: bricks-mysql
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bricks-network

volumes:
  mysql_data:

networks:
  bricks-network: